//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp5666
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int serviceID { get; set; }
        public string type { get; set; }
        public string price { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
